/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisitantesRouteImport } from './routes/visitantes'
import { Route as SistemaRouteImport } from './routes/sistema'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as OfertasRouteImport } from './routes/ofertas'
import { Route as MetasRouteImport } from './routes/metas'
import { Route as MembrosRouteImport } from './routes/membros'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EventosRouteImport } from './routes/eventos'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as AuditoriaRouteImport } from './routes/auditoria'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AcessoNegadoRouteImport } from './routes/acesso-negado'
import { Route as IndexRouteImport } from './routes/index'

const VisitantesRoute = VisitantesRouteImport.update({
  id: '/visitantes',
  path: '/visitantes',
  getParentRoute: () => rootRouteImport,
} as any)
const SistemaRoute = SistemaRouteImport.update({
  id: '/sistema',
  path: '/sistema',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const OfertasRoute = OfertasRouteImport.update({
  id: '/ofertas',
  path: '/ofertas',
  getParentRoute: () => rootRouteImport,
} as any)
const MetasRoute = MetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => rootRouteImport,
} as any)
const MembrosRoute = MembrosRouteImport.update({
  id: '/membros',
  path: '/membros',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosRoute = EventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditoriaRoute = AuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AcessoNegadoRoute = AcessoNegadoRouteImport.update({
  id: '/acesso-negado',
  path: '/acesso-negado',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acesso-negado': typeof AcessoNegadoRoute
  '/admin': typeof AdminRoute
  '/auditoria': typeof AuditoriaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/eventos': typeof EventosRoute
  '/login': typeof LoginRoute
  '/membros': typeof MembrosRoute
  '/metas': typeof MetasRoute
  '/ofertas': typeof OfertasRoute
  '/perfil': typeof PerfilRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sistema': typeof SistemaRoute
  '/visitantes': typeof VisitantesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acesso-negado': typeof AcessoNegadoRoute
  '/admin': typeof AdminRoute
  '/auditoria': typeof AuditoriaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/eventos': typeof EventosRoute
  '/login': typeof LoginRoute
  '/membros': typeof MembrosRoute
  '/metas': typeof MetasRoute
  '/ofertas': typeof OfertasRoute
  '/perfil': typeof PerfilRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sistema': typeof SistemaRoute
  '/visitantes': typeof VisitantesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acesso-negado': typeof AcessoNegadoRoute
  '/admin': typeof AdminRoute
  '/auditoria': typeof AuditoriaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/eventos': typeof EventosRoute
  '/login': typeof LoginRoute
  '/membros': typeof MembrosRoute
  '/metas': typeof MetasRoute
  '/ofertas': typeof OfertasRoute
  '/perfil': typeof PerfilRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sistema': typeof SistemaRoute
  '/visitantes': typeof VisitantesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acesso-negado'
    | '/admin'
    | '/auditoria'
    | '/configuracoes'
    | '/eventos'
    | '/login'
    | '/membros'
    | '/metas'
    | '/ofertas'
    | '/perfil'
    | '/reset-password'
    | '/sistema'
    | '/visitantes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acesso-negado'
    | '/admin'
    | '/auditoria'
    | '/configuracoes'
    | '/eventos'
    | '/login'
    | '/membros'
    | '/metas'
    | '/ofertas'
    | '/perfil'
    | '/reset-password'
    | '/sistema'
    | '/visitantes'
  id:
    | '__root__'
    | '/'
    | '/acesso-negado'
    | '/admin'
    | '/auditoria'
    | '/configuracoes'
    | '/eventos'
    | '/login'
    | '/membros'
    | '/metas'
    | '/ofertas'
    | '/perfil'
    | '/reset-password'
    | '/sistema'
    | '/visitantes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcessoNegadoRoute: typeof AcessoNegadoRoute
  AdminRoute: typeof AdminRoute
  AuditoriaRoute: typeof AuditoriaRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  EventosRoute: typeof EventosRoute
  LoginRoute: typeof LoginRoute
  MembrosRoute: typeof MembrosRoute
  MetasRoute: typeof MetasRoute
  OfertasRoute: typeof OfertasRoute
  PerfilRoute: typeof PerfilRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SistemaRoute: typeof SistemaRoute
  VisitantesRoute: typeof VisitantesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visitantes': {
      id: '/visitantes'
      path: '/visitantes'
      fullPath: '/visitantes'
      preLoaderRoute: typeof VisitantesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sistema': {
      id: '/sistema'
      path: '/sistema'
      fullPath: '/sistema'
      preLoaderRoute: typeof SistemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ofertas': {
      id: '/ofertas'
      path: '/ofertas'
      fullPath: '/ofertas'
      preLoaderRoute: typeof OfertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metas': {
      id: '/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof MetasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membros': {
      id: '/membros'
      path: '/membros'
      fullPath: '/membros'
      preLoaderRoute: typeof MembrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos': {
      id: '/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof EventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auditoria': {
      id: '/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuditoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acesso-negado': {
      id: '/acesso-negado'
      path: '/acesso-negado'
      fullPath: '/acesso-negado'
      preLoaderRoute: typeof AcessoNegadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcessoNegadoRoute: AcessoNegadoRoute,
  AdminRoute: AdminRoute,
  AuditoriaRoute: AuditoriaRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  EventosRoute: EventosRoute,
  LoginRoute: LoginRoute,
  MembrosRoute: MembrosRoute,
  MetasRoute: MetasRoute,
  OfertasRoute: OfertasRoute,
  PerfilRoute: PerfilRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SistemaRoute: SistemaRoute,
  VisitantesRoute: VisitantesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
